import requests

def currency_api(key):
    """
    Currencyapi --> https://app.currencyapi.com/
    :param key: API Key.
    :return: String com as cotações de todas as moedas disponíveis na API.
    """
    moedas_all = {
        'USD': 'Dólar Americano',
        'EUR': 'Euro',
        'GPB': 'Libra esterlina',
        'JPY': 'Iene japonês',
        'CHF': 'Franco suíço',
        'CAD': 'Dólar canadense',
        'AUD': 'Dólar Australiano',
        'RUB': 'Rublo russo',
        'ARS': 'Peso argentino',
        'AED': 'Dirham dos Emirados Árabes Unidos',
        'AFN': 'Afegane afegão',
        'ALL': 'Lek albanês',
        'AMD': 'Dram armênio',
        'ANG': 'Florim das Antilhas Holandesas',
        'AOA': 'Kwanza angolano',
        'AWG': 'Florim arubano',
        'AZN': 'Manat azeri',
        'BAM': 'Marco conversível da Bósnia e Herzegovina',
        'BBD': 'Dólar barbadense',
        'BDT': 'Taka bengali',
        'BGN': 'Lev búlgaro',
        'BHD': 'Dinar bareinita',
        'BIF': 'Franco burundiano',
        'BMD': 'Dólar bermudense',
        'BND': 'Dólar bruneano',
        'BOB': 'Boliviano da Bolívia',
        'BRL': 'Real Brasileiro',
        'BSD': 'Dólar bahamense',
        'BTN': 'Ngultrum butanês',
        'BWP': 'Pula botsuanesa',
        'BYN': 'Rublo bielorrusso',
        'BZD': 'Dólar belizenho',
        'CDF': 'Franco congolês',
        'CLF': 'Unidades de Fomento chilenas',
        'CLP': 'Peso chileno',
        'CNY': 'Remimbi',
        'COP': 'Peso colombiano',
        'CRC': 'Colón costarriquenho',
        'CUP': 'Peso cubano',
        'CUC': 'Peso conversível',
        'CVE': 'Escudo cabo-verdiano',
        'CZK': 'Coroa tcheca',
        'DJF': 'Franco do Djibouti',
        'DKK': 'Coroa dinamarquesa',
        'DOP': 'Peso dominicano',
        'DZD': 'Dinar argelino',
        'EGP': 'Libra egípcia',
        'ETB': 'Birr etíope',
        'FJD': 'Dólar fijiano',
        'GEL': 'Lari georgiano',
        'GHS': 'Cedi ganês',
        'GMD': 'Dalasi gambiano',
        'GNF': 'Franco guineano',
        'GTQ': 'Quetzal guatemalteco',
        'GYD': 'Dólar guianense',
        'HKD': 'Dólar de Hong Kong',
        'HNL': 'Lempira hondurenha',
        'HRK': 'Kuna croata',
        'HTG': 'Gourde haitiano',
        'HUF': 'Florim húngaro',
        'IDR': 'Rupia indonésia',
        'ILS': 'Novo shekel israelense',
        'INR': 'Rupia indiana',
        'IQD': 'Dinar iraquiano',
        'IRR': 'Rial iraniano',
        'ISK': 'Coroa islandesa',
        'JMD': 'Dólar jamaicano',
        'JOD': 'Dinar jordaniano',
        'KES': 'Xelim queniano',
        'KGS': 'Som quirguiz',
        'KHR': 'Riel',
        'KMF': 'Franco comoriano',
        'KRW': 'Won sul-coreano',
        'KWD': 'Dinar kuwaitiano',
        'KYD': 'Dólar das Ilhas Cayman',
        'KZT': 'Tenge cazaque',
        'LAK': 'Kip laosiano',
        'LBP': 'Libra libanesa',
        'LKR': 'Rupia cingalesa',
        'LRD': 'Dólar Liberiano',
        'LSL': 'Loti lesotiano',
        'LTL': 'Litas lituano',
        'LVL': 'Lats letão',
        'LYD': 'Dinar líbio',
        'MAD': 'Dirham marroquino',
        'MDL': 'Leu moldávio',
        'MGA': 'Ariary malgaxe',
        'MKD': 'Dinar macedônio',
        'MMK': 'Quiate',
        'MOP': 'Pataca',
        'MRO': 'Ouguiya mauritana',
        'MUR': 'Rupia Mauriciana',
        'MVR': 'Rupia maldívia',
        'MWK': 'Kwacha malauiana',
        'MXN': 'Peso mexicano',
        'MYR': 'Ringgit malaio',
        'MZN': 'Metical moçambicano',
        'NAD': 'Dólar namibiano',
        'NGN': 'Naira nigeriana',
        'NIO': 'Córdoba nicaraguense',
        'NOK': 'Coroa norueguesa',
        'NPR': 'Rupia nepalesa',
        'NZD': 'Dólar neozelandês',
        'OMR': 'Rial omanense',
        'PAB': 'Balboa panamenho',
        'PEN': 'Novo sol peruano',
        'PGK': 'Kina papuásia',
        'PHP': 'Peso filipino',
        'PKR': 'Rúpia Paquistanesa',
        'PLN': 'Zloty polonês',
        'PYG': 'Guarani paraguaio',
        'QAR': 'Rial catariano',
        'RON': 'Leu romeno',
        'RSD': 'Dinar sérvio',
        'RWF': 'Franco ruandês',
        'SAR': 'Riyal saudita',
        'SBD': 'Dólar das Ilhas Salomão',
        'SCR': 'Rupia das Seychelles',
        'SDG': 'Libra Sudanesa',
        'SEK': 'Coroa sueca',
        'SGD': 'Dólar singapuriano',
        'SHP': 'Libra de Santa Helena',
        'SLL': 'Leone de Serra Leoa',
        'SOS': 'Xelim somali',
        'SRD': 'Dólar surinamês',
        'STD': 'Dobra de São Tomé e Príncipe',
        'SVC': 'Colom salvadorenho',
        'SZL': 'Lilangeni suazi',
        'THB': 'Baht tailandês',
        'TJS': 'Somoni',
        'TMT': 'Manat turcomano',
        'TND': 'Dinar tunisiano',
        'TOP': 'Paʻanga tonganesa',
        'TRY': 'Lira turca',
        'TTD': 'Dólar de Trinidad e Tobago',
        'TWD': 'Novo dólar taiwanês',
        'TZS': 'Xelim tanzaniano',
        'UAH': 'Hryvnia ucraniano',
        'UGX': 'Xelim Ugandês',
        'UYU': 'Peso uruguaio',
        'UZS': 'Som uzbeque',
        'VND': 'Dong vietnamita',
        'XAF': 'Franco CFA Central',
        'XCD': 'Dólar do Caribe Oriental',
        'XOF': 'Franco CFA ocidental',
        'XPF': 'Franco CFP',
        'YER': 'Rial iemenita',
        'ZAR': 'Rand sul-africano',
        'ZMK': 'Kwacha zambiano',
        'ZMW': 'Kwacha zambiano',
        'ZWL': 'Dólar do Zimbabwe'
    }

    res = requests.get(f'https://api.currencyapi.com/v3/latest?apikey={key}&base_currency=BRL').json()
    last_updated = res['meta']['last_updated_at']
    moedas = [moeda for moeda in res['data']]
    quantidade_moedas = len(moedas_all)
    texto1 = f'{quantidade_moedas} Moedas\n({last_updated})\n\n'  # Moedas importantes
    texto2 = str()  # Moedas Secundárias



    c = 0
    while c < quantidade_moedas:
        moeda = moedas[c]
        code, valor = res['data'][moeda]['code'], str(round(1/res['data'][moeda]['value'], 6)).replace('.', ',')
        if code in moedas_all:
            texto1 += f'1 {code} ({moedas_all[code]}) = R$ {valor}\n'
        else:
            texto2 += f'1 {code} = R$ {valor}\n'
        c += 1

    return texto1 + texto2
